name: 'AI Content Review Test and Development'
description: 'Test setup for AI Content Review functionality to make development of the feature easier.'
type: 'AI Initiative'
recipes:
  - core/recipes/page_content_type

install:
  - ai_content_review
  - ai_agents
  - ai_agents_debugger
  - token_entity_render

config:
  strict: false
  actions:
    ai.settings:
      verifySetupAi:
        operation_type_has_default_model:
          - chat_with_tools